//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeckoDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public Booking()
        {
            this.Session = new HashSet<Session>();
        }
    
        public int Id { get; set; }
        public string BookingDate { get; set; }
        public decimal TotalCost { get; set; }
        public bool IsDeleted { get; set; }
        public int UserId { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<Session> Session { get; set; }
    }
}
