//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeckoDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Session
    {
        public int SessionID { get; set; }
        public System.DateTime StartDateTime { get; set; }
        public System.DateTime EndDateTime { get; set; }
        public decimal SessionCost { get; set; }
        public bool IsDeleted { get; set; }
        public int BookingBookingID { get; set; }
        public int CourtCourtID { get; set; }
    
        public virtual Booking Booking { get; set; }
        public virtual Court Court { get; set; }
    }
}
